   program PINGPONG
   USE MPI
   
   INTEGER :: RANK, IERROR
   INTEGER :: status(MPI_STATUS_SIZE)
   REAL, DIMENSION(10) :: A, B

   CALL MPI_INIT(IERROR)
   CALL MPI_COMM_RANK(MPI_COMM_WORLD, RANK, IERROR)

   IF (RANK .EQ. 0) THEN
      PRINT *,'node',RANK,' PINGPONG_MPI - PING'
      CALL MPI_SEND(A, 10, MPI_REAL, 1, 0, MPI_COMM_WORLD, &
      IERROR)
   ELSE IF (RANK .EQ. 1) THEN
      PRINT *,'node',RANK,' PINGPONG_MPI - PING'
      CALL MPI_RECV(B, 10, MPI_REAL, 0, 0, MPI_COMM_WORLD, &
      status, IERROR)
   END IF

   IF (RANK .EQ. 0) THEN
      PRINT *,'node',RANK,' PINGPONG_MPI - PONG'
      CALL MPI_RECV(A, 10, MPI_REAL, 1, 0, MPI_COMM_WORLD, &
      IERROR)
   ELSE IF (RANK .EQ. 1) THEN
      PRINT *,'node',RANK,' PINGPONG_MPI - PONG'
      CALL MPI_SEND(B, 10, MPI_REAL, 0, 0, MPI_COMM_WORLD, &
      status, IERROR)
   END IF

   CALL MPI_FINALIZE(IERROR)
   if (RANK == 0) then
       print *,'node',RANK,' finishing normally'
   end if
END PROGRAM PINGPONG
